module.exports = {
  enumData: {
    pricings: ["Thường", "Đồng", "Bạc", "Vàng", "Kim cương"],
    postStatus: ["Còn trống", "Đang đàm phán", "Đã bàn giao"],
    propertyTypes: [
      "Căn hộ chung cư",
      "Nhà mặt phố",
      "Nhà riêng",
      "Nhà phố thương mại",
      "Biệt thự",
      "Đất nền",
      "Bán đất",
      "Trang trại",
      "Khu nghĩ dưỡng",
      "Kho",
      "Nhà xưởng",
      "Khác",
    ],
    listingTypes: ["Bán", "Cho thuê"],
    directions: ["Đông - Bắc", "Tây - Nam", "Đông - Nam", "Tây - Bắc", "Đông", "Tây", "Nam", "Bắc"],
  },
  pricings: [
    {
      name: "Thường",
      isDisplayImmedialy: false,
      levelShowDescription: 0.1,
      priority: 1, // độ ưu tiên của tin đăng
      requireScore: 0,
      requiredScoreNextLevel: 200000,
      expiredDay: 1,
      price: 0,
      imageUrl: "/svg/badge-stock/base.svg",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Đồng",
      isDisplayImmedialy: false,
      levelShowDescription: 0.2,
      priority: 2, // độ ưu tiên của tin đăng
      requireScore: 200000,
      requiredScoreNextLevel: 500000,
      expiredDay: 3,
      price: 200000,
      imageUrl: "/svg/badge-stock/bronze.svg",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Bạc",
      isDisplayImmedialy: true,
      levelShowDescription: 0.3,
      priority: 3, // độ ưu tiên của tin đăng
      requireScore: 500000,
      requiredScoreNextLevel: 1000000,
      expiredDay: 7,
      price: 500000,
      imageUrl: "/svg/badge-stock/silver.svg",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Vàng",
      isDisplayImmedialy: true,
      levelShowDescription: 0.4,
      priority: 4, // độ ưu tiên của tin đăng
      requireScore: 1000000,
      requiredScoreNextLevel: 2000000,
      expiredDay: 10,
      price: 1000000,
      imageUrl: "/svg/badge-stock/gold.svg",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Kim cương",
      isDisplayImmedialy: true,
      levelShowDescription: 0.5,
      priority: 5, // độ ưu tiên của tin đăng
      requireScore: 2000000,
      requiredScoreNextLevel: -1,
      expiredDay: 15,
      price: 2000000,
      imageUrl: "/svg/badge-stock/diamond.svg",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
}
